const worldTag = [
    { description: "Abandoned Colony" },
    { description: "Alien Ruins" },
    { description: "Altered Humanity" },
    { description: "Anarchists" },
    { description: "Anthropomorphs" },
    { description: "Area 51" },
    { description: "Badlands World" },
    { description: "Battleground" },
    { description: "Beastmasters" },
    { description: "Bubble Cities" },
    { description: "Cheap Life" },
    { description: "Civil War" },
    { description: "Cold War" },
    { description: "Colonized Population" },
    { description: "Cultural Power" },
    { description: "Cybercommunists" },
    { description: "Cyborgs" },
    { description: "Cyclical Doom" },
    { description: "Desert World" },
    { description: "Doomed World" },
    { description: "Dying Race" },
    { description: "Eugenic Cult" },
    { description: "Exchange Consulate" },
    { description: "Fallen Hegemon" },
    { description: "Feral World" },
    { description: "Flying Cities" },
    { description: "Forbidden Tech" },
    { description: "Former Warriors" },
    { description: "Freak Geology" },
    { description: "Freak Weather" },
    { description: "Friendly Foe" },
    { description: "Gold Rush" },
    { description: "Great Work" },
    { description: "Hatred" },
    { description: "Heavy Industry" },
    { description: "Heavy Mining" },
    { description: "Hivemind" },
    { description: "Holy War" },
    { description: "Hostile Biosphere" },
    { description: "Hostile Space" },
    { description: "Immortals" },
    { description: "Local Specialty" },
    { description: "Local Tech" },
    { description: "Major Spaceyard" },
    { description: "Mandarinate" },
    { description: "Mandate Base" },
    { description: "Maneaters" },
    { description: "Megacorps" },
    { description: "Mercenaries" },
    { description: "Minimal Contact" },
    { description: "Misandry/Misogyny" },
    { description: "Night World" },
    { description: "Nomads" },
    { description: "Oceanic World" },
    { description: "Out of Contact" },
    { description: "Outpost World" },
    { description: "Perimeter Agency" },
    { description: "Pilgrimage Site" },
    { description: "Pleasure World" },
    { description: "Police State" },
    { description: "Post-Scarcity" },
    { description: "Preceptor Archive" },
    { description: "Pretech Cultists" },
    { description: "Primitive Aliens" },
    { description: "Prison Planet" },
    { description: "Psionics Academy" },
    { description: "Psionics Fear" },
    { description: "Psionics Worship" },
    { description: "Quarantined World" },
    { description: "Radioactive World" },
    { description: "Refugees" },
    { description: "Regional Hegemon" },
    { description: "Restrictive Laws" },
    { description: "Revanchists" },
    { description: "Revolutionaries" },
    { description: "Rigid Culture" },
    { description: "Rising Hegemon" },
    { description: "Ritual Combat" },
    { description: "Robots" },
    { description: "Seagoing Cities" },
    { description: "Sealed Menace" },
    { description: "Secret Masters" },
    { description: "Sectarians" },
    { description: "Seismic Instability" },
    { description: "Shackled World" },
    { description: "Societal Despair" },
    { description: "Sole Supplier" },
    { description: "Taboo Treasure" },
    { description: "Terraform Failure" },
    { description: "Theocracy" },
    { description: "Tomb World" },
    { description: "Trade Hub" },
    { description: "Tyranny" },
    { description: "Unbraked AI" },
    { description: "Urbanized Surface" },
    { description: "Utopia" },
    { description: "Warlords" },
    { description: "Xenophiles" },
    { description: "Xenophobes" },
    { description: "Zombies" }
  ];
  
  export {worldTag };